#!/bin/bash

set -e

# Retrieve arguments
domain=$1
path=$2
user=$3
ipaddr="$(ip a s dev eth0 | grep -oP 'inet\s+\K[^/]+')"
echo $user
echo $ipaddr

# Check user parameter
sudo yunohost user list --json | grep -qi "\"username\": \"$user\"" \
	|| (echo "User does not exist: $user" && exit 1)
sudo yunohost app setting dockershipyard admin_user -v $user

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a dockershipyard \
	|| (echo "Path not available: $domain$path" && exit 1)

# Remove trailing "/" for next commands
path=${path%/}

# Check ports availability
sudo yunohost app checkport 4243
if [[ ! $? -eq 0 ]]; then
  exit 1
fi
sudo yunohost app checkport 8080
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# Install Docker if it is not installed yet
if [ -f /usr/bin/docker ]; then
	echo "Docker is already installed"
else
	echo "Docker will now be installed"
	sudo apt-get install curl -y -qq
	sudo curl -sSL https://get.docker.com/ | sh
	sudo yunohost service add docker
	sudo update-rc.d docker defaults
	sudo service docker start 
	sudo usermod -aG docker admin
	newgrp docker
fi
# Allow Docker to listen to port 4243 and fix DOCKER_OPTS
sudo cp ../conf/docker.service /lib/systemd/system/docker.service
sudo chmod 644 /lib/systemd/system/docker.service
sudo sed -i "s@DOCKER_OPTS=\"-d-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock\"@@g" /etc/default/docker
sudo sh -c "echo 'DOCKER_OPTS=\"-d-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock\"' >> /etc/default/docker"
sudo service docker restart

# Create Shipyard containers
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock shipyard/deploy start

# Change Shipyard settings
sudo yunohost firewall allow TCP 8080 > /dev/null 2>&1
docker run -ti --rm shipyard/shipyard-cli
shipyard login
http://$ipaddr:8080
admin
shipyard
# Create admin user
# find external ip alternative : curl ipecho.net/plain ; echo
#shipyard add-account -u demo -p demo123 -r admin
#shipyard delete-account admin

# Add local engine
shipyard add-engine --id local --addr http://$ipaddr:4243 --cpus 1.0 --memory 1024 --label local
exit


# Configure Nginx and reload
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/dockershipyard.conf
sudo service nginx reload
echo $?