#!/bin/bash

set -e

# Retrieve arguments
domain=$1
path=$2
user=$3
ipaddr="ip a s dev eth0 | grep -oP 'inet\s+\K[^/]+'"

# Check user parameter
sudo yunohost user list --json | grep -qi "\"username\": \"$user\"" \
	|| (echo "User does not exist: $user" && exit 1)
sudo yunohost app setting dockershipyard admin_user -v $user

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a dockershipyard \
	|| (echo "Path not available: $domain$path" && exit 1)

# Remove trailing "/" for next commands
path=${path%/}

# Check ports availability
sudo yunohost app checkport 4243
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# Install Docker if it is not installed yet
if [ -f /usr/bin/docker ]; then
	echo "Docker is already installed"
else
	echo "Docker will now be installed"
	sudo apt-get install curl -y -qq
	sudo curl -sSL https://get.docker.com/ | sh
	sudo yunohost service add docker
	sudo update-rc.d docker defaults
	sudo service docker start 
	sudo usermod -aG docker admin
	newgrp docker
fi
# Allow Docker to listen to port 4243 and fix DOCKER_OPTS
sudo sh -c "echo 'DOCKER_OPTS=\"-d-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock\"' >> /etc/default/docker"
sudo sed -i "s@DOCKER_OPTS\n=@DOCKER_OPTS=/etc/default/docker\n@g" /etc/init.d/docker
sudo service docker restart

# Create Shipyard containers
sudo docker run -it -d --name shipyard-rethinkdb-data \
    --entrypoint /bin/bash shipyard/rethinkdb -l
sudo docker run -it -P -d --name shipyard-rethinkdb \
    --volumes-from shipyard-rethinkdb-data shipyard/rethinkdb
sudo docker run -it -p 8080:8080 -d --name shipyard \
    --link shipyard-rethinkdb:rethinkdb shipyard/shipyard

# Create admin user
# docker run --rm -it shipyard/shipyard-cli
# shipyard login
# $ip
# admin
# shipyard
# find external ip alternative : curl ipecho.net/plain ; echo

# Add local engine

# Redirect Shipyard


# Configure Nginx and reload
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/dockershipyard.conf
sudo service nginx reload
echo $?